[package]
name = "rotatar-types"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
thiserror.workspace = true
serde = { version = "1.0.219", features = ["derive"] }
better_default = "1.0.5"
serde-inline-default = "0.2.3"
